config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    collection do
      delete 'batch_delete'
      get 'batch_edit'
      put 'batch_update'
    end
  end
  get 'welcome/index'

  root 'candidates#index'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base

	# validates_of_uniqueness :name
	validates_uniqueness_of :name,:message=>"The name #{name} is taken."
	validates :name, length:{maxinum: 5,minimum: 2}
	# before_validation :candidate_validation

	private
	
	  def candidate_validation
	  	is_exists = Candidate.all.exists?(:name=>self.name)
	  	# binding.pry
	  	!is_exists
	  	# self.message = 1
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
	
	def index
    	@candidates = Candidate.all
    end
	
	def show
    	@candidate = Candidate.find(params[:id])
  	end

  	def edit
	  @candidate = Candidate.find(params[:id])
	end

	def new
	end

	def create
			# render plain: params[:candidate].inspect
		@candidate = Candidate.new(candidate_params)
 		# binding.pry
		is_save = @candidate.save
		# binding.pry
		# redirect_to @candidate
		#is_save ? (redirect_to @candidate) : (flash.now[:notice] = "Post failed created!!!")
		binding.pry
		if is_save
			flash[:notice] = "Post created!!!"
			redirect_to @candidate
		else
			flash[:notice] = "Post created false!!!"
			render :new
		end
	end

	def batch_delete
		# binding.pry
		Candidate.destroy(params[:candidates]) unless params[:candidates].blank?
		redirect_to :back
	end

	def batch_edit
		@candidates = Candidate.find(params[:candidates]) unless params[:candidates].blank?
		# Candidate.destroy(params[:candidates]) unless params[:candidates].blank?
		render 'edits'
	end

	def batch_update
		@candidates_list = params[:candidate_ids] unless params[:candidate_ids].blank?
		@candidates_list.each do |candidate|
			@candidate = Candidate.find(candidate.first)
			@candidate.update_attribute(candidate.last.keys.first, candidate.last.values.first)		
		end
		# Candidate.destroy(params[:candidates]) unless params[:candidates].blank?
		redirect_to action: "index"
		# redirect_to action: "index"
	end

	def destroy
	    @candidate = Candidate.where("id = ?", params[:id]).first
	    @candidate.destroy
		#redirect_to :back
		redirect_to action: "index"
	    #render :index

	     # respond_to do |format|
	     #   format.html { redirect_to :controller => "candidate" , :action => "index" }
	     #   format.xml  { head :ok }
	     # end
  	end
	
	def update
		@candidate = Candidate.find(params[:id])
		# binding.pry
		count = @candidate.attributes["votenum"]
		count = 0 if !count
		@candidate.update_attribute(:votenum, count + 1)
		redirect_to :back
		  # if @candidate.update(candidate_params)
		  #   redirect_to @candidates
		  # else
		  #   render 'index'
		  # end
	end


	private

	  def candidate_params
	    params.require(:candidate).permit(:name)
	  end
	  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/candidates/edit.html.erb
<%= form_for :candidate, url:candidates_path do |f| %>
	<p>
	  <strong>ID:</strong>
	  <%= @candidate.id %>
	</p>
  <p>
    <%= f.label :name %>: <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit "Update", :onclick => "return confirm('Edit?')" %>
  </p>
<% end %>

app/views/candidates/edits.html.erb
<%=form_tag batch_update_candidates_path, :method=>:put, :multipart=>true do %>

<h1>Listing candidates</h1>
 
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Vote Num</th>
  </tr>
	  <% for  candidate in @candidates %>
	  	
		 <tr>
		 <td><%=candidate.id %></td>
		 <td><%=candidate.name %></td>
		 	<td>
		    <%=fields_for("candidate_ids[]", candidate) do |f| %>
		     <%=f.text_field :votenum  %>
		     <% end %>
		     </td>
		 </tr>

	  <% end %>
  <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
  </tr>
  <tr> <td colspan="4"><p><%=submit_tag "Save All"%></p></td></tr>
</table>

<% content_for(:head) do %>
  <%= javascript_include_tag 'candidates.js' %>
<% end %>

<% end %>

app/views/candidates/index.html.erb
<%=form_tag 'main',:name => 'mainform' do %>
<h1>Listing candidates</h1>
 
<table>
  <tr>
    <th></th>
    <th>ID</th>
    <th>Name</th>
    <th>Vote Num</th>
    <th>Vote</th>
    <th>Delete</th>
    <th>Edit</th>
  </tr>
  <% @candidates.each do |candidate| %>
    <tr>
      <td><%= check_box_tag "candidates[]", candidate.id %></td>
      <td><%= candidate.id %></td>
      <td><%= candidate.name %></td>
      <td><%= candidate.votenum %></td>
      <td><%= link_to "Vote #{candidate.name}",{:controller => :candidates, :action => :update, :id => candidate.id },:method => :put %> </td>
  <!--     <td><%= button_to "Vote #{candidate.name}",:id => candidate.id %> </td> -->
      <td><%= link_to "delete", {:controller => :candidates, :action => :destroy, :id => candidate.id }, :method => :delete %></td>
      <td><%= link_to "edit", {:controller => :candidates, :action => :edit, :id => candidate.id }, :method => :get %></td>
    </tr>
  <% end %>
  <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td><a href="" id="delete_selected" onclick="beforesubmit(this);" >delete selected</a></td>
   <!--  <td><p><%=button_to "delete selected", {:controller => :candidates, :action => 'batch_delete' }, :method => :delete %></p></td> -->
    <!-- <a href="javascript:beforesubmit();" data-method='delete' >Delete selected</a> -->
<!--     <input type="button" value="Delete selected" onclick = beforesubmit($("form[name='mainform']")) /></td> -->
    <td><a href="" id="edit_selected" onclick="beforesubmit(this);" >edit selected</a></td>

  </tr>
  <tr> <td colspan="4"><p><%=link_to "Add Candidates", new_candidate_path %></p></td></tr>
</table>

<% content_for(:head) do %>
  <%= javascript_include_tag 'candidates.js' %>
<% end %>

<% end %>

app/views/candidates/new.html.erb
<%= form_for :candidate, url:candidates_path do |f| %>
  <p>
    <%= f.label :name %>: <%= f.text_field :name %>
  </p>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
  <p>
    <%= f.submit "Save", :onclick => "return confirm('Sure?')" %>
  </p>
<% end %>

app/views/candidates/show.html.erb
<p>
  <strong>ID:</strong>
  <%= @candidate.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @candidate.name %>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
</p>
 
<p>
  <strong>votenum:</strong>
  <%= @candidate.votenum %>
</p>

<p><%=link_to "Back to List", candidates_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>